### ISSUE TITLE
[Feature Request] Blacklist support (NSFW skin)

### ISSUE THREAD

**Issue by arturek1666** [SkinsRestorer/SkinSystem#31]
I would love to be able to prevent people from uploading naked skins as it's not friendly. Would this be possible?

**Comment by riflowth** [comment]
Oh, I hadn't thought about that. 😢 Thanks for request this feature. I will research & development for this issue.

**Comment by ITZVGcGPmO** [comment]
sounds like a job for a neural network :thinking:

**Comment by riflowth** [comment]
https://github.com/riflowth/LearningX
@ITZVGcGPmO I'm learning about AI. but ........... LMAO !! 😢 😆

**Comment by arturek1666** [comment]
As it was in 2019 and it will not be worked on closing.
